GET http://localhost:3001/api/ping

###
GET http://localhost:3001/api/diagnoses


###
GET http://localhost:3001/api/patients


###
POST http://localhost:3001/api/patients HTTP/1.1 
content-type: application/json

{
    "name": "Test Person2",
    "dateOfBirth": "1976-07-09",
    "gender": "male",
    "occupation": "something",
    "ssn": "1234567V124"
}


###
POST http://localhost:3001/api/patients/d2773c6e-f723-11e9-8f0b-362b9e155667 HTTP/1.1 
content-type: application/json

{
  "description": "test",
  "date": "2021-01-01",
  "specialist": "MD House",
  "type": "Hospital",
  "diagnosisCodes": ["M24.2", "M51.2"],
  "discharge": {
    "date": "2021-01-01",
    "criteria": "something"
  }
}


###
POST http://localhost:3001/api/patients/d2773c6e-f723-11e9-8f0b-362b9e155667 HTTP/1.1 
content-type: application/json

{
  "description": "test",
  "date": "2021-01-01",
  "specialist": "MD House",
  "type": "OccupationalHealthcare",
  "employerName": "NSA",
  "sickLeave": {
    "startDate": "2022-01-01",
    "endDate": "2022-02-02"
  }

}

###
POST http://localhost:3001/api/patients/d2773c6e-f723-11e9-8f0b-362b9e155667 HTTP/1.1 
content-type: application/json

{
  "description": "test",
  "date": "2021-01-01",
  "specialist": "MD House",
  "type": "HealthCheck",
  "healthCheckRating": "2"

}
